services:
  - type: web
    name: lifeisstrangecall
    runtime: node
    buildCommand: npm install --production
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
